### ISSUE TITLE
TypeScript error: intersectsTriangle not recognized on boundsTree.shapecast()

### ISSUE THREAD

**Issue by kjetil-bugge-kristoffersen-adsk** [gkjohnson/three-mesh-bvh#840]
### Description

After upgrading from 0.9.4 to 0.9.7, TypeScript rejects intersectsTriangle callback in shapecast() calls on geometry.boundsTree.                      
                                                                                                                                                        
The root cause: boundsTree is typed as GeometryBVH, but computeBoundsTree() returns MeshBVH by default. Since intersectsTriangle is only defined on MeshBVH.shapecast() (not the base ShapecastCallbacks interface), TypeScript errors:
```                                                                                                                                                       
error TS2561: Object literal may only specify known properties, but 'intersectsTriangle' does not exist in type 'ShapecastCallbacks'.
```

The code works at runtime since boundsTree is actually a MeshBVH instance.                     

Introduced in: commit https://github.com/gkjohnson/three-mesh-bvh/commit/ade609eb55e195bc252ac814c9c4c1d4dc51271b ("Update shapecast dts", Jan 8 2026)

### Reproduction steps

1. Create a mesh and compute bounds tree
2. Call shapecast with intersectsTriangle
3. TypeScript reports error on intersectsTriangle

### Code

```ts
const geometry = new BoxGeometry();                                                                                                                   geometry.computeBoundsTree(); 
geometry.boundsTree!.shapecast({
    intersectsBounds: (box) => box.intersectsBox(targetBox)
    intersectsTriangle: (tri) => {
      // TypeScript error here
      return false;
    },
  });
```

### Live example

hard to setup type bugs like this online

### Screenshots

N/A - this is a type-only error, no visual/runtime issue

### Library Version

0.9.7

### Three.js Version

0.182.0

**Comment by timothyallan** [comment]
just saw this report, I was checking release notes to see if intersectsTriangle had been killed off!

**Comment by gkjohnson** [comment]
See https://github.com/gkjohnson/three-mesh-bvh/issues/824

With the changes to the project to support more general BVH classes the "shapecast" callbacks were reworked to make sense for non-triangle primitives but [intersectsTriangle is still defined for MeshBVH.shapecast](https://github.com/gkjohnson/three-mesh-bvh/blob/29c017713879ef80eb6b46cfe5dd3f61c9e1c825/src/index.d.ts#L164-L173). I'm not an expert in typescript so I'll need some direction and a PR on how this can be handled. From #824:

> I'm not super familiar with typescript so I'm not sure if there are ways, for instance, to ducktype the GeometryBVH based on the arguments or based on access (eg if you access "boundsTree" from a geometry assigned to a Mesh then it should be expected to be a MeshBVH). But otherwise for an immediate fix you can explicitly cast the boundsTree to MeshBVH.
